### ISSUE TITLE
Page load performance mentioned is outdated

### ISSUE THREAD

**Issue by hotdogc1017** [vuejs/docs#3176]
In the [performance optimization page](https://vuejs.org/guide/best-practices/performance.html#overview), the title [Overview](https://vuejs.org/guide/best-practices/performance.html#overview) mentions `FID`, but this web metric has been replaced by `INP`. The [page](https://web.dev/articles/fid) that the document links to also shows a warning

**Comment by mahmudunnabikajal** [comment]
@hotdogc1017  Hope the issue has been resolved.

reference: #3150

**Comment by hotdogc1017** [comment]
Yes, the content of the English version has been updated, but the Chinese version is still the same as before. This should be a problem with the internationalization of the document.
